# -*- coding: utf-8 -*-
"""26_05_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrCBPkJYlTjB_3iys4oSGloJQlOk8ITe
"""

print ("Привет мир")